name: Build x86/64/ Linux 6.12
on: [push]

jobs:
    build:
        name: Prepare and Build x86/64/ Linux 6.12 Images
        runs-on: ubuntu-latest

        steps:
            - name: Setup Ubuntu
              run: |
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages


                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply  01-cpu.patch
                git apply 20-lxc.patch
                cd -
                sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "195s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd

                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                cp .github/workflows/config.buildinfo86 .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/23edc25efeb65ef69d8eb6598f4f8179/raw/29c862e3e2558852523f4e8edd5f3d0cc145067e/01-key.patch
                git apply 01-key.patch
                make download -j32
                rm 01-key.patch
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/x86/64/packages
                echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
                echo "HASH=$(git log -1 --format="%H")" >> $GITHUB_ENV
            - name: Delete tag
              run: gh release delete x86-6.12 --cleanup-tag || true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                commit: ${{ env.HASH }}
                name: x86/64/ Linux 6.12 Images ${{ env.DATE }}
                tag: x86-6.12
                replacesArtifacts: true
                prerelease: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: bin/targets/x86/64/*

